services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - minitwit-network
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/dashboards/:/etc/grafana/provisioning/dashboards/
    ports:
      - "3000:3000"
    networks:
      - minitwit-network

  minitwit:
    image: minitwit-monitoring:latest
    volumes:
      - ./db/:/db/
    ports:
      - target: 8080
        published: 8081 
        mode: ingress
    networks:
      - minitwit-network
    deploy:
      replicas: 3           
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s


networks:
  minitwit-network:
    external: false
    name: minitwit-network