{
 "title": "Minitwit requests",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status of Server",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"minitwit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99'th percentile of request time",
   "type": "gauge",
   "description": "The 99'th percentile of time to complete request in the last 5 minutes. Meaning that 99% of all requests are completed in this time or less.",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(request_duration_bucket{path!=\"/metrics\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99.9'th percentile of request time",
   "type": "gauge",
   "description": "The 99.9'th percentile of time to complete request in the last 5 minutes. Meaning that 99.9% of all requests are completed in this time or less. Effectively the maximum time a request can be expected to take",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by(le) (rate(request_duration_bucket{path!=\"/metrics\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. Request Time",
   "type": "timeseries",
   "description": "The time it takes to process a request averaged over the last minute",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(request_duration_sum{path!=\"/metrics\"}[1m]) / (rate(request_duration_count{path!=\"/metrics\"}[1m]))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Avg requests pr. second",
   "type": "timeseries",
   "description": "The average request to the server pr. second over a 1 minute window",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 6 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(requests_count{path!=\"/metrics\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Follow requests pr. second",
   "type": "timeseries",
   "description": "The average number of follow requests made pr. second over a 1 minute window",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(requests_count{path=\"/fllws/{username}\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Register requests pr. second",
   "type": "timeseries",
   "description": "The average number of register requests made pr. second over a 1 minute window",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "rate(requests_count{path=\"/register\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Tweet Requests pr. second ",
   "type": "timeseries",
   "description": "The average number of tweet request made pr second over a 1 minute window",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "rate(requests_count{path=\"/msgs/{username}\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Minitwit logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"minitwit\"}"
    }
   ]
  }
 ]
}