{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Tweet requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "tweet_request_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Follow requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "follow_request_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Register requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "register_request_count", "legendFormat": "__auto" }
   ]
  }
 ]
}