all:
  vars:
    ansible_user: <user>
  hosts:
    app:
      ansible_host: <insert-droplet-ip>
      ansible_connection: ssh
      ansible_ssh_private_key_file: ~/.ssh/<key-name>
    monitor:
      ansible_host: <insert-droplet-ip>
      ansible_connection: ssh
      ansible_ssh_private_key_file: ~/.ssh/<key-name>   
    test_droplet:
      ansible_host: <insert-droplet-ip>
      ansible_connection: ssh
      ansible_ssh_private_key_file: ~/.ssh/<key-name>

  children: 
    prod:
      hosts:
        app:
        monitor:
    test:
      hosts:
        test_droplet: