name: Test and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run checks
        uses: dagger/dagger-for-github@27b130bf0f79a7f6fbbbe0fbca6760dc9bb40a77
        with:
          check: "**"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "latest"
      - name: Run end2end
        uses: dagger/dagger-for-github@27b130bf0f79a7f6fbbbe0fbca6760dc9bb40a77
        with:
          module: .
          args: e-2-e
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "latest"

  build:
    needs: test
    if: success() 
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v6.2.0
        with:
          go-version: '1.25'
      - name: Build binary
        run: "go build -o ./minitwit ./src/main.go"
      - name: Zip project
        run: "tar -zcvf minitwit.tar.gz minitwit README.md static templates"
      - name: Auto Changelog
        uses: ardalanamini/auto-changelog@v4.0.1
        id  : changelog
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-types: |
              feat: New Features
              fix: Bug Fixes
              build: Build System & Dependencies
              perf: Performance Improvements
              docs: Documentation
              test: Tests
              refactor: Refactors
              chore: Chores
              ci: CI
              cd: CD
              ci/cd: CI/CD
              style: Code Style
              revert: Reverts
      - name: Create release
        uses: softprops/action-gh-release@v2.5.0
        with:
          body: ${{steps.changelog.outputs.changelog}}
          files: "*.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    needs: test
    if: success() 
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: actions/checkout@v4
      - name: Publish
        uses: dagger/dagger-for-github@v8.3.0
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          version: "latest"
          verb: call
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          module: .
          args: publish --src=. --username=${{ secrets.DOCKER_USERNAME }} --password=DOCKER_PASSWORD
  provision:
    needs: publish
    if: success()
    name: provision
    runs-on: ubuntu-latest
    env:
      PUB_APP_IP: ${{ secrets.PUB_APP_IP }}
      PUB_MONITOR_IP: ${{ secrets.PUB_MONITOR_IP }}
      PUB_TEST_IP: ${{ secrets.PUB_TEST_IP }}
    steps:
      - name: Setup environment
        uses: actions/checkout@v4
      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@dc588b651fe13675774614f8e6a936a468676387
        with:
          ssh-private-key: |
            ${{ secrets.SSH_KEY_APP }}
            ${{ secrets.SSH_KEY_MONITOR }}
      - name: Add All Targets to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.PUB_APP_IP }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.PUB_MONITOR_IP }} >> ~/.ssh/known_hosts
      - name: Manual Ansible Setup and Provision
        run: |
          pip install ansible
          cd ansible && ansible-playbook -i example_inventory.yml playbook.yml --limit "prod"
        env: 
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          DB_SSL_MODE: disable
          MONITOR_IP: ${{ secrets.MONITOR_IP }}
          CONTAINER_NAME_PREFIX: minitwit
          NOIP_USERNAME: ${{ secrets.NOIP_USERNAME }}
          NOIP_PASSWORD: ${{ secrets.NOIP_PASSWORD }}
          NOIP_HOSTNAMES: ${{ secrets.NOIP_HOSTNAMES }}
          CERTBOT_EMAIL: ${{ secrets.CERTBOT_EMAIL }}
          POSTGRES_CPU_LIMIT: 0.5
          POSTGRES_MEM_LIMIT: 512M
          APP_REPLICAS: 3
          DIGITAL_OCEAN_TOKEN: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          MONITOR_PUB_KEY: ${{ secrets.MONITOR_PUB_KEY }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
          DROPLET_USERNAME: ${{ secrets.DROPLET_USERNAME }}




            

