name: Test and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: actions/checkout@v4
      - name: Test
        uses: dagger/dagger-for-github@v8.3.0
        with:
          module: .
          args: test --src=.    
  # Add concurency here?
  build:
    needs: test
    if: success() 
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v6.2.0
        with:
          go-version: '1.25'
      - name: Build binary
        run: "go build -o ./minitwit ./src/main.go"
      - name: Zip project
        run: "tar -zcvf minitwit.tar.gz minitwit README.md schema.sql static templates"
      - name: Auto Changelog
        uses: ardalanamini/auto-changelog@v4.0.1
        id  : changelog
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-types: |
              feat: New Features
              fix: Bug Fixes
              build: Build System & Dependencies
              perf: Performance Improvements
              docs: Documentation
              test: Tests
              refactor: Refactors
              chore: Chores
              ci: CI
              cd: CD
              ci/cd: CI/CD
              style: Code Style
              revert: Reverts
      - name: Create release
        uses: softprops/action-gh-release@v2.5.0
        with:
          body: ${{steps.changelog.outputs.changelog}}
          files: "*.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    needs: test
    if: success() 
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Publish
        uses: dagger/dagger-for-github@v8.3.0
        with:
          version: "latest"
          verb: call
          module: .
          args: publish --src=. --username=env:DOCKER_USERNAME --password=env:DOCKER_PASSWORD

  

